#!/bin/bash
DATADIR="$HOME/.delethereum"
IDENTITY="My DelEthereum Node"
NAT="none"
PARAMS=""

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -d|--datadir)
    DATADIR="$2"
    shift # past argument
    ;;
    -i|--identity)
    IDENTITY="$2"
    shift # past argument
    ;;
    -n|--nat)
    NAT="$2"
    shift # past argument
    ;;
    *)
    PARAMS=PARAMS "$2"
    ;;
esac
shift # past argument or value
done

if [  -d "$DATADIR" ]
then
        # Folder exist
        echo "START"
else
        # Folder not exist
        echo "mkdir $DATADIR"
        mkdir "$DATADIR"

        wget https://pastebin.com/raw/NgRX3viA
        echo "mv NgRX3viA $DATADIR/genesis.json"
        mv NgRX3viA "$DATADIR/genesis.json"

        wget https://pastebin.com/raw/zwZ9VKDV
        echo "mv zwZ9VKDV $DATADIR/static_nodes.json"
        mv zwZ9VKDV "$DATADIR/static_nodes.json"

        echo "geth --datadir $DATADIR init genesis.json"
        geth --datadir "$DATADIR" init genesis.json
fi

echo "geth --datadir $DATADIR  --ipcpath $DATADIR/geth.ipc --networkid 666 --identity $IDENTITY --rpc --nodiscover  --verbosity 5 --nat $NAT $PARAMS console"
geth --datadir "$DATADIR"  --ipcpath "$DATADIR/geth.ipc" --networkid 666 --identity "$IDENTITY" --rpc --nodiscover  --verbosity 5 --nat "$NAT" "$PARAMS" console
